%% This function generates Gaussian and Laplacian Image Pyramids

function [GaussianPyr, LaplacianPyr] = generateImagePyramids(fullImg, a, pyrLevels)

%% Make sure that the image is of the proper size format
[rows, cols] = size(fullImg);
cropRows = 0;
cropCols = 0;

if mod(rows-1, 2^pyrLevels) > 0
    cropRows = mod(rows-1, 2^pyrLevels);
end

if mod(cols-1, 2^pyrLevels) > 0
    cropCols = mod(cols-1, 2^pyrLevels);
end

img = fullImg(1 : (rows - cropRows), 1 : (cols - cropCols));

%% Initialize the gaussian row and column operators
gRow = [(0.25 - 0.5*a), 0.25, a, 0.25, (0.25 - 0.5*a)];
gCol = [(0.25 - 0.5*a); 0.25; a; 0.25; (0.25 - 0.5*a)];

%% Gaussian Pyramid
% The first level of the gaussian pyramid is the image itself
% The pyramid is generated by successively blurring and subsampling the
% image by half.
GaussianPyr = {img};
for i = 1 : pyrLevels - 1
    tempImg = GaussianPyr{i};
    % Row blurring
    tempBlurRowImg = imfilter(tempImg, gRow, 'replicate');
    % Column blurring on the row blurred image
    tempBlurImg = imfilter(tempBlurRowImg, gCol, 'replicate');
    % Subsample by half
    tempSubsampled = imresize(tempBlurImg, 0.5);
    % Store in the gaussian pyramid
    GaussianPyr = vertcat(GaussianPyr, tempSubsampled);
end

%% Laplacian Pyramid
% The laplacian pyramid is generated by interpolating the i+1 level image
% to the size of the i level and then taking a difference and storing it in
% the pyramid.
LaplacianPyr = {};
for i = 1 : pyrLevels - 1
    % the i level image
    tempImg1 = GaussianPyr{i};
    % the i+1 level image
    tempImg2 = GaussianPyr{i + 1};
    % interpolating the i+1 level image to the size of i level image
    tempImg2Scaled = imresize(tempImg2, size(tempImg1));
    % taking the difference to get the error
    laplacianImg = tempImg1 - tempImg2Scaled;
    % storing in the laplacian pyramid
    LaplacianPyr = vertcat(LaplacianPyr, laplacianImg);
end

% the last level of the laplacian pyramid is nothing other than the last
% level of the gaussian pyramid.
LaplacianPyr = vertcat(LaplacianPyr, GaussianPyr(pyrLevels));

end